### ISSUE TITLE
Doesn't work in FF and Chrome

### ISSUE THREAD

**Issue by satalways** [lukemorton/jquery-caret#1]
This plugin doesn't work in FireFox and Google Chrome. Can anyone provide better solution?

**Comment by lukemorton** [comment]
What version of FireFox and Google Chrome are you using? I've got it working in Google Chrome 14 and FireFox 5 on Windows 7.

**Comment by satalways** [comment]
I'm using Chrome 14.0.835.163 and FF 6.0.2

**Comment by lukemorton** [comment]
Would you like to share your example so I can have a try myself?

**Comment by satalways** [comment]
Yes sure,
I'm using this...

$('#home, #office').focus(function(){
    $(this).caretToEnd();
});

**Comment by lukemorton** [comment]
Put it in a setTimeout() closure like so:

```
$('#home, #office').focus(function() {
    var $this = $(this);
    setTimeout(function () {
        $this.caretToEnd();
    }, 13);
});
```

Delaying it allows you to let the first focus happen then jump to the end.

**Comment by satalways** [comment]
Thank you very much, It is working fine......... and issue is resolved.

**Comment by lukemorton** [comment]
No problem I was glad to be of some help. Feel free to report any other problems you may find.

**Comment by lukemorton** [comment]
I was thinking you could also use $.fn.delay (in jQuery 1.4+) like so:

```
$('#home, #office').focus(function() {
    $(this).delay(13).caretToEnd();
});
```

**Comment by satalways** [comment]
Yes it is also working,
Thank you very much.

**Comment by satalways** [comment]
I suggest you to embed this code in your library. So built in delay should be there in caretToEnd method.
What do you think?

**Comment by lukemorton** [comment]
The delay is used only to get around the way browsers handle the `focus` event. If you changed the event to `click` then you would not need the delay (see: [example.html](https://github.com/DrPheltRight/jquery-caret/blob/master/example.html)).

By adding the delay function to the plugin I would be providing a solution for focus when it is not needed in other use cases. After all it's only 9+ characters added to your JS so it's small price to pay for getting focus to work with $.fn.caret() I think. Maybe you disagree?

**Comment by satalways** [comment]
If it doesn't work with focus() then it is a bug.

**Comment by lukemorton** [comment]
If you can suggest a way to only use setTimeout or $.fn.delay when inside a `focus` event callback then by all means submit a Pull Request. However I'm not too sure there is a way although I'm going to have a look into it over my lunch.

**Comment by lukemorton** [comment]
Okay I've looked into it and the general consensus seems to be that the focus event is not cancellable in any browser. Therefore using a timeout is the only thing you can do to get around this problem.

Again as this only affects the focus event I don't think $.fn.caret should provide the shim to make it work. How does $.fn.caret() know if you are calling it within a focus callback? It cannot know this and therefore it shouldn't solve this problem.

**Comment by satalways** [comment]
Thank you very much for your help, Previous solution is enough for me and working fine.

**Comment by lukemorton** [comment]
No problems again glad I could help :)
